### ISSUE TITLE
Feature Request: 1.21 Port

### ISSUE THREAD

**Issue by PowerGamer12** [o7Moon/OpenBoatUtils#62]
Hi, I'd love to see this updated to 1.21 to use on my newest server!

**Comment by muggelpotato** [comment]
I would kill for a port to 1.21

**Comment by LordEnder-Kitty** [comment]
There's a pull request that has an updated version. Please can this mod be updated?! I can't play half the tracks on the server i boat race on because they need this mod and i use 1.21. I don't want to make a specific thing in an older version on atlauncher just to boat race. i just want to use my regular mods in the default game launcher. Surely it can't be that hard to update it. I've looked through the code. It doesn't look that difficult.

**Comment by o7Moon** [comment]
> Surely it can't be that hard to update it. I've looked through the code. It doesn't look that difficult.

It isn't but I'm quite busy. The biggest hurdle is learning the new networking api and being sure that the new implementation's packets match the old ones.

see https://github.com/o7Moon/OpenBoatUtils/issues/65 for my plans, though it may be a while before this happens. 

As far as I know racing servers are still on 1.20.X, and the best version to play on would be 1.20.4 (even after obu supports 1.21).

**Comment by muggelpotato** [comment]
thank you :)

**Comment by muggelpotato** [comment]
@o7Moon does removal of fixes for dedicated servers mean that the mod doesnt function on dedicated servers anymore?
and what were the previous fixes?

**Comment by o7Moon** [comment]
> @o7Moon does removal of fixes for dedicated servers mean that the mod doesnt function on dedicated servers anymore? and what were the previous fixes?

@muggelpotato 

obu is a clientside mod, with commands added to the internal server for testing in singleplayer. this was getting used by dedicated servers to use the client mod instead of proper server mods/plugins using packet api. 
there used to be mixins in obu to remove dedicated server specific movement checks that would prevent boat stepping, those no longer exist. 
iirc spigot/paper servers have a certain configuration for these movement checks that servers like boatlabs are using but i dont personally know what the options are. 
if you're writing a fabric server mod [this](https://github.com/o7Moon/OpenBoatUtils/blob/0.4/src/main/java/dev/o7moon/openboatutils/mixin/ServerPlayNetworkHandlerMixin2.java) is the now removed file with those mixins, they arent very heavily tested and i cant guarantee they still work in 1.21

**Comment by muggelpotato** [comment]
I wish I'd be capable of writing a server mod.
unfortunatly this is just the best boat physics altering mod there is and we heavily rely on it.
fyi, when trying to execute one of the testing commands on a 1.21 server you'll get disconnected with the following error:
`Internal Exception: io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:custom_payload' (openboatutils:settings)`
