### ISSUE TITLE
mode not working properly

### ISSUE THREAD

**Issue by Utku494** [o7Moon/OpenBoatUtils#63]
The reason I downloaded this mod is that normally in the game we can't go over a block high block with the bot and even though I downloaded and installed this mod, the problem still persists.

**Comment by o7Moon** [comment]
openboatutils extends the client so that the server can modify boat physics. if you aren't the server, then you have no control over if stepping is enabled, and it isn't enabled by default.
if you are playing in singleplayer, then you *are* the server, and there are commands you can use to change the settings (for example you can make the boat step up blocks by running the command `/stepsize 1.25`). these commands are only meant for testing and aren't as well supported as the packet api but you can use the mod this way if you need to.
if you are running a server and want to use openboatutils to enable stepping, you will have to have a plugin (or mod, depending on your server software) on your server to do that, using [the packet api](https://github.com/o7Moon/OpenBoatUtils/wiki/Packets).

**Comment by Utku494** [comment]
thank you man!!!!
