### ISSUE TITLE
CRITICAL: 0.4.2 does not apply airspeed in any mode

### ISSUE THREAD

**Issue by Sotumney** [o7Moon/OpenBoatUtils#79]
Whether using the local blockslipperiness command for air or applying a boatmode, airspeed never works.

This is a critical bug and renders the mod broken.

**Comment by o7Moon** [comment]
okay, testing across 1.21 and 1.21.1 right now

**Comment by o7Moon** [comment]
happens on both

**Comment by o7Moon** [comment]
remove the release from modrinth and github for now, will have to figure out why this happens

**Comment by o7Moon** [comment]
ah, shit, i think its because of changes on my local branch that didn't get reverted and were included in the build, nothing in the repo code.
im going to do a proper build and test it first, then re-release 0.4.2 but bump the version ID so servers can differentiate this new build from the broken one.

**Comment by o7Moon** [comment]
both modrinth and github releases should now have the fixed jar, the broken build didn't have too many downloads but servers need to check for version ID `8` if they want to prevent it from being used :(
